FROM ghcr.io/graalvm/native-image-community:20 AS build

WORKDIR /app
ADD . /app
RUN mvn package -Pnative

FROM debian:12

WORKDIR /app
COPY --from=build /app/target/rinhabackend /app/rinhabackend
ENTRYPOINT [ "./rinhabackend" ]